// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYkEmnzFNlRs-Bogah5rPqVMmAYEiJW-U',
    appId: '1:977613763925:web:d64d3aff30a0f4bfa56bdc',
    messagingSenderId: '977613763925',
    projectId: 'onlypass-customer-app',
    authDomain: 'onlypass-customer-app.firebaseapp.com',
    storageBucket: 'onlypass-customer-app.appspot.com',
    measurementId: 'G-40Y0LGHNHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZnV5aNJnFlHYWlMfHw687oY6WqG0mftI',
    appId: '1:977613763925:android:3e4a6650ba8eb8f1a56bdc',
    messagingSenderId: '977613763925',
    projectId: 'onlypass-customer-app',
    storageBucket: 'onlypass-customer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqIJ92PpIWMUjmUxDMLn2MkXGcmsR044',
    appId: '1:977613763925:ios:ce691d5637a5626aa56bdc',
    messagingSenderId: '977613763925',
    projectId: 'onlypass-customer-app',
    storageBucket: 'onlypass-customer-app.appspot.com',
    iosBundleId: 'com.example.onlypass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTqIJ92PpIWMUjmUxDMLn2MkXGcmsR044',
    appId: '1:977613763925:ios:ce691d5637a5626aa56bdc',
    messagingSenderId: '977613763925',
    projectId: 'onlypass-customer-app',
    storageBucket: 'onlypass-customer-app.appspot.com',
    iosBundleId: 'com.example.onlypass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYkEmnzFNlRs-Bogah5rPqVMmAYEiJW-U',
    appId: '1:977613763925:web:c2f5142d99380665a56bdc',
    messagingSenderId: '977613763925',
    projectId: 'onlypass-customer-app',
    authDomain: 'onlypass-customer-app.firebaseapp.com',
    storageBucket: 'onlypass-customer-app.appspot.com',
    measurementId: 'G-JDNL0NPHTQ',
  );

}